# 차원 - 미니퀘스트

## 1번 퀘스트
다음 NumPy 배열의 차원 수를 출력하는 코드를 작성하세요.



```
import numpy as np
array = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
```



In [ ]:
import numpy as np
array = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
print(array.ndim)
print(np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]]).ndim)

3
3


## 2번 퀘스트
1차원 배열 [10, 20, 30, 40, 50, 60]을 2차원 배열로 변환하여 (2, 3) 형태로 출력하는 코드를 작성하세요.

In [ ]:
matrix = np.array([10, 20, 30, 40, 50, 60]).reshape(2, 3)
print(matrix)

[[10 20 30]
 [40 50 60]]


## 3번 퀘스트
다음 1차원 배열에 새로운 차원을 추가하여 2차원 배열로 변환하고, 최종 배열의 차원 수를 출력하세요.
- newaxis를 사용하여 배열의 차원을 추가하고, 새로운 차원에서의 배열 모양을 확인한 후 최종 차원 수를 출력하세요.


```
import numpy as np
array = np.array([7, 14, 21])
```



In [ ]:
# 1. newaxis로 배열의 차원 추가
# 2. 새로운 차원에서의 배열 모양 확인
# 3. 최종 차원 수 출력
import numpy as np

# 원본 배열
vector = np.array([7, 14, 21])

# 차원 추가
column_vector = vector[:, np.newaxis]

print("원본 배열:", vector)

print("차원을 추가한 배열:\n", column_vector)

print("최종 차원 수", column_vector.ndim)

원본 배열: [ 7 14 21]
차원을 추가한 배열:
 [[ 7]
 [14]
 [21]]
최종 차원 수 2


# Shape - 미니퀘스트

## 1번 퀘스트
주어진 2차원 NumPy 배열의 형태(Shape)를 출력하는 코드를 작성하세요.


```
import numpy as np
array = np.array([[1, 2, 3], [4, 5, 6]])
```



In [ ]:
import numpy as np
array = np.array([[1, 2, 3], [4, 5, 6]])
print(array.shape)

(2, 3)


## 2번 퀘스트
1차원 배열 [10, 20, 30, 40, 50, 60]을 (2, 3) 형태로 변경한 후, 새로운 배열의 형태를 출력하는 코드를 작성하세요.

In [ ]:
import numpy as np
array = np.array([10, 20, 30, 40, 50, 60])
reshaped_array = array.reshape(2, 3)
print(reshaped_array)

[[10 20 30]
 [40 50 60]]


## 3번 퀘스트
다음 1차원 배열의 형태를 변경하여 (3, 2, 2) 형태로 조정하고, 최종 배열의 형태를 출력하는 코드를 작성하세요

```
import numpy as np
array = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])
```



In [ ]:
import numpy as np
array = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])
reshaped_array = array.reshape(3, 2, 2)
print(reshaped_array.ndim)

3


# 데이터 타입 - 미니퀘스트

## 1번 퀘스트
아래의 NumPy 배열의 데이터 타입을 확인하는 코드를 작성하세요.


```
import numpy as np
array = np.array([10, 20, 30])
```



In [ ]:
import numpy as np
array = np.array([10, 20, 30])
print(array.dtype)

int64


## 2번 퀘스트
정수형 배열 [1, 2, 3]을 부동소수점형 배열로 변환하고, 변환된 배열의 데이터 타입을 출력하는 코드를 작성하세요.

In [ ]:
import numpy as np
array = np.array([1, 2, 3])

converted_array = array.astype(np.float64)
print(converted_array.dtype)

float64


## 3번 퀘스트
NumPy 배열 [100, 200, 300]을 uint8로 변환한 수, 메모리 사용량(바이트)을 출력하는 코드를 작성하세요.

In [ ]:
import numpy as np
array = np.array([100, 200, 300])

converted_array = array.astype(np.uint8)
print(converted_array.nbytes)

3


# 인덱싱 - 미니퀘스트

## 1번 퀘스트
주어진 1차원 배열에서 첫 번째 요소와 마지막 요소를 출력하는 코드를 작성하세요.

```
import numpy as np
array = np.array([10, 20, 30, 40, 50])
```



In [ ]:
import numpy as np
array = np.array([10, 20, 30, 40, 50])
print(array[0])
print(array[-1])

10
50


##2번 퀘스트
주어진 2차원 배열에서 첫번째 열과 두번째 행을 출력하는 코드를 작성하세요.


```
import numpy as np
matrix = np.array([
  [1, 2, 3],
  [4, 5, 6],
  [7, 8, 9]
])
```



In [ ]:
import numpy as np
matrix = np.array([
  [1, 2, 3],
  [4, 5, 6],
  [7, 8, 9]
])
print(matrix[:, 0])
print(matrix[1, :])

[1 4 7]
[4 5 6]


## 3번 퀘스트
주어진 배열에서 10보다 큰 요소들만 선택하고, 해당 요소들의 인덱스를 출력하는 코드를 작성하세요.


```
import numpy as np
array = np.array([5, 15, 8, 20, 3, 12])
```



In [ ]:
import numpy as np
array = np.array([5, 15, 8, 20, 3, 12])

filtered = array[array > 10]
print('filtered: ', filtered)

filtered:  [15 20 12]


# 연산 - 미니퀘스트

## 1번 퀘스트
주어진 NumPy 배열에서 요소별(Element-wise) 덧셈을 수행하는 코드를 작성하세요.


```
import numpy as np
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
```



In [ ]:
import numpy as np
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

print('a + b: ', a + b)

a + b:  [5 7 9]


## 2번 퀘스트
다음 NumPy 배열에서 브로드캐스팅을 활용하여 각 행에 [1, 2, 3]을 더하는 코드를 작성하세요.


```
import numpy as np
matrix = np.array([[10, 20, 30], [40, 50, 60]])
vector = np.array([1, 2, 3])
```



In [ ]:
import numpy as np
matrix = np.array([[10, 20, 30], [40, 50, 60]])
vector = np.array([1, 2, 3])

result = matrix + vector
print("matrix + vector:\n", result)

matrix + vector:
 [[11 22 33]
 [41 52 63]]


## 3번 퀘스트
주어진 2차원 NumPy 배열에 대해, 축(axis)을 기준으로 최댓값을 구하고 최종 배열의 차원을 출력하는 코드를 작성하세ㅔ요.


```
import numpy as np
array = np.array([[3, 7, 2], [8, 4, 6]])
```



In [ ]:
import numpy as np
array = np.array([[3, 7, 2], [8, 4, 6]])
max_axis0 = np.max(array, axis=0)
print(max_axis0)
print(max_axis0.ndim)

max_axis1 = np.max(array, axis=1)
print(max_axis1)
print(max_axis1.ndim)

[8 7 6]
1
[7 8]
1


# 유니버설 함수 - 미니퀘스트

## 1번 퀘스트
배열 [1, 2, 3, 4]에 대해 NumPy의 유니버설 함수를 사용하여 모든 요소를 제곱한 결과를 출력하는 코드를 작성하세요.

In [ ]:
import numpy as np

values = np.array([1, 2, 3, 4])
print("np.square(values):", np.square(values))

np.square(values): [ 1  4  9 16]


## 2번 퀘스트
다음 두 배열의 요소별 합을 계산하고, 결과를 새로운 배열이 아닌 기존 배열에 저장하는 코드를 작성하세요.


```
array1 = np.array([10, 20, 30])
array2 = np.array([1, 2, 3])
```



In [ ]:
import numpy as np

array1 = np.array([10, 20, 30])
array2 = np.array([1, 2, 3])

np.add(array1, array2, out=array1)
print(array1)

[11 22 33]


## 3번 퀘스트
다음 배열에 대해 NumPy 유니버설 함수를 사용하여 요소별로 자연로그(log)를 계산하고, 특정 조건(log 값 > 1)을 만족하는 요소만 출력하는 코드를 작성하세요.


```
array = np.array([1, np.e, 10, 100])
```



In [ ]:
import numpy as np

array = np.array([1, np.e, 10, 100])

result = array[np.log(array) > 1]
print(result)

[ 10. 100.]
